export const coreCommittee = [
	{
		id: 1,
		name: "Arnab Chatterjee",
		designation: "President",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 2,
		name: "Debarjun Thakur",
		designation: "Vice-President",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 3,
		name: "Ishita Bej",
		designation: "Secretary",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 4,
		name: "Subhayan Mukherjee",
		designation: "Treasurer",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 5,
		name: "Sagnik Mukherjee",
		designation: "Event Coordinator",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 6,
		name: "Vikash Kumar Pandey",
		designation: "Outreach Coordinator",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 7,
		name: "Soumyajit Chattaraj",
		designation: "Management Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 8,
		name: "Amartya Chowdhury",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 9,
		name: "Sayandeep Pal",
		designation: "Events Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 10,
		name: "Swarup Goswami",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 11,
		name: "Subham Guha",
		designation: "Socials & PR Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 12,
		name: "Aditi Hazra",
		designation: "Socials & PR Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
];

export const techTeam = [
	{
		id: 1,
		name: "Asif Qamar",
		designation: "Tech Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 2,
		name: "Avik Ghosh",
		designation: "Web Development",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 3,
		name: "Elhan Yasir",
		designation: "Tech Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 4,
		name: "Fatima Aslam",
		designation: "Machine Learning",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 5,
		name: "Khushi Singh",
		designation: "Tech Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 6,
		name: "Monu Kumar Singh",
		designation: "Competitive Programming",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 7,
		name: "Nilam Kumari Mahato",
		designation: "Tech Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 8,
		name: "Pinaki Ranjan Pal",
		designation: "Web Development",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 9,
		name: "Prantor Das",
		designation: "Web Development",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 10,
		name: "Prasoon Kumar",
		designation: "Web Development",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 11,
		name: "Princi Kumari",
		designation: "UI/UX Designer",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 12,
		name: "Prerna Priya",
		designation: "Tech Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 13,
		name: "Pravanjan Roy",
		designation: "Web Development",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 14,
		name: "Rishika Kaur",
		designation: "Machine Learning",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 15,
		name: "Roshan Kumar",
		designation: "Tech Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 16,
		name: "Souvik Majee",
		designation: "Tech Team",
		image: "/DevsocHero.png",
		link: "#",
	},
];

export const managementTeam = [
	{
		id: 1,
		name: "Amrit Kumar",
		designation: "Event Management & PR",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 2,
		name: "Ankur Kumar Sah",
		designation: "Member",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 3,
		name: "Anurag Singh",
		designation: "Event Management & PR",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 4,
		name: "Mehroof Saba",
		designation: "Management Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 5,
		name: "Nikhil Gupta",
		designation: "Event Management & PR",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 6,
		name: "Prajakta Sarkhel",
		designation: "Management Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 7,
		name: "Sana Chakraborty",
		designation: "Management Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 8,
		name: "Sanjay Sharma",
		designation: "Event Management & PR",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 9,
		name: "Supriyo Das",
		designation: "Management Team",
		image: "/DevsocHero.png",
		link: "#",
	},
];

export const designTeam = [
	{
		id: 1,
		name: "Achhat Kumar Gupta",
		designation: "Graphics Designer",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 2,
		name: "Arpita Sharma",
		designation: "Design Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 3,
		name: "Ayushi Kumari Shaw",
		designation: "Design Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 4,
		name: "Gourav Yadav",
		designation: "Design Team",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 5,
		name: "Saikat Sinha",
		designation: "Graphics Designer",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 6,
		name: "Sohom Paul",
		designation: "Video Editor",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 7,
		name: "Taniya Digar",
		designation: "Design Team",
		image: "/DevsocHero.png",
		link: "#",
	},
];
