export const committeeMembers = [
	{
		id: 1,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 2,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 3,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 4,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 5,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 6,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 7,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 8,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 9,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 10,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
];

export const subCommitteeMembers = [
	{
		id: 1,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 2,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 3,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 4,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 5,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 6,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 7,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 8,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 9,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
	{
		id: 10,
		name: "XYZ Kumar",
		designation: "Tech Lead",
		image: "/DevsocHero.png",
		link: "#",
	},
];
